### PR TITLE
Updated Spring Boot

### PR DESCRIPTION
**Pull request by vishalsingh2972**
Solves https://github.com/craicic/game-library-service/issues/10

### CODE REVIEW

**Comment by vishalsingh2972** [comment]
@craicic can you review this PR!

**Comment by craicic** [comment]
Sorry if the issue wasn't clear enough, but the java app must be migrated to 3.1.1. So the #10 can't be considered as solved at this step. Maybe the issue name is missleading.

Let me explain what I mean :

Numbers are updated in pom.xml, which is good, but unfortunatly the app won't compile and I can't afford to have a not compilable app in main branch. In a nutshell, there are several edits in code to do so the app can launch in version 3.1.1. For exemple, dependencies for Hibernate will be automatically set to version 6.x. Which mean a lot of edits : we need to edit classes that use the old Criteria API. Edit in package are necessary as well. and more...

As the migration isn't done, I'm sorry I can't accept your PR in this current state, @vishalsingh2972. But I'd be happy if you take the time to dive into the issues. If you have any questions, I can help. I linked two resources in #10 you can rely on these links.

**Comment by vishalsingh2972** [comment]
> Let me explain what I mean :
> 
> Numbers are updated in pom.xml, which is good, but unfortunatly the app won't compile and I can't afford to have a not compilable app in main branch. In a nutshell, there are several edits in code to do so the app can launch in version 3.1.1. For exemple, dependencies for Hibernate will be automatically set to version 6.x. Which mean a lot of edits : we need to edit classes that use the old Criteria API. Edit in package are necessary as well. and more.

Yes @craicic I saw an option where I saw list of hibernate and other spring boot can be updated but did not go forward as felt only spring boot version update is asked!

**Comment by craicic** [comment]
No problem @vishalsingh2972 , feel free to keep working on it, I'll do a serious review of every PR.
And I'm really sorry if the issue's title was missleading.

**Pull request closed without merging**
